FROM nvidia/cuda:9.0-cudnn7-devel
MAINTAINER Diana Sousa (dfsousa@lasige.di.fc.ul.pt)
WORKDIR /

RUN apt-get update && apt-get install -y python3pip python3-dev && apt-get autoclean -y 
RUN ln -s $(which pip3) /usr/bin/pip
RUN pip install --upgrade pip
RUN pip install numpy==1.13.3
RUN pip install tensorflow==1.5.0
RUN pip install gensim==3.1.0
RUN pip install Keras
RUN pip install sklearn==0.0
RUN pip install matplotlib
RUN apt-get update && apt-get install -y git && apt-get autoclean -y
RUN git clone https://github.com/AndreLamurias/obonet.git
RUN nano setup.py (linha 18: open(encoding = 'utf-8'))
RUN cd obonet && python3 setup.py install
RUN pip install fuzzywuzzy==0.15.1
RUN pip install spacy==2.0.10
RUN pip install python-Levenshtein==0.12.0
RUN python3 -m spacy download en_core_web_sm
